<a href="https://colab.research.google.com/github/MethEthPro/colab/blob/main/nlp/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=cf0ab7d944a233a582271487695bb2969ed616cb60f7055d4937ba158ad2a44d
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget


In [ ]:
import gensim.downloader as api

model = api.load("word2vec-google-news-300")  # Loads the model directly


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
model.most_similar('robber')

[('armed_robber', 0.7991542220115662),
 ('robbers', 0.796387255191803),
 ('masked_robber', 0.7416025996208191),
 ('thief', 0.736222505569458),
 ('bandit', 0.7240806818008423),
 ('knife_wielding_robber', 0.7169459462165833),
 ('purse_snatcher', 0.705200731754303),
 ('burglar', 0.70276939868927),
 ('robbery', 0.7020812630653381),
 ('carjacker', 0.6939209699630737)]

In [ ]:
model.most_similar('bollywood')

[('Bollywood', 0.8250343203544617),
 ('Kollywood', 0.775660514831543),
 ('Tollywood', 0.7674685120582581),
 ('Salman_Khan', 0.7204594016075134),
 ('tinsel_town', 0.7178173661231995),
 ('Kareena_Kapoor', 0.7131139636039734),
 ('filmi', 0.7074834704399109),
 ('Telugu_cinema', 0.704646646976471),
 ('Deepika_Padukone', 0.699794352054596),
 ('Katrina_Kaif', 0.6966326236724854)]

In [ ]:
model.most_similar("India")

[('Indias', 0.7384199500083923),
 ('Indiaâ_€_™', 0.6843485832214355),
 ('Pakistan', 0.6706860661506653),
 ('Delhi', 0.6632035374641418),
 ('Bangalore', 0.6583030819892883),
 ('subcontinent', 0.6579218506813049),
 ('Bangladesh', 0.6527796983718872),
 ('sub_continent', 0.6503037810325623),
 ('Mumbai', 0.6495688557624817),
 ('Sri_Lanka', 0.6445952653884888)]

In [ ]:
model.similarity('man','woman')

0.76640123

In [ ]:
model.similarity('python','snake')

0.66062933

In [ ]:
model.doesnt_match(['python','cobra','java'])

'java'

In [ ]:
model.doesnt_match(['php','snake','java'])

'snake'

In [ ]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [ ]:
vec = model['sword'] + model['japan']
model.most_similar(vec)

[('japan', 0.7726046442985535),
 ('sword', 0.6919801235198975),
 ('katana', 0.5768263936042786),
 ('japanese', 0.5680861473083496),
 ('warhammer', 0.5652372241020203),
 ('shogun', 0.5513859987258911),
 ('swords', 0.5435155034065247),
 ('alexander', 0.5336614847183228),
 ('okami', 0.5309876799583435),
 ('samurai', 0.5218623280525208)]

# GAME OF THRONES WORD2VEC

In [3]:
import numpy as np
import pandas as pd

In [4]:
!pip install gensim

In [5]:
import gensim
import os

In [ ]:
!kaggle datasets download -d khulasasndh/game-of-thrones-books


Dataset URL: https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books
License(s): unknown
100% 3.71M/3.71M [00:01<00:00, 4.89MB/s]
100% 3.71M/3.71M [00:01<00:00, 3.61MB/s]


In [ ]:
!unzip -q game-of-thrones-books.zip -d my_extracted_data


In [ ]:
import nltk

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
import chardet

file_path = os.path.join('my_extracted_data', filename)

# Read a sample of the file in binary mode to detect encoding
with open(file_path, "rb") as f:
    raw_data = f.read(10000)  # Read first 10,000 bytes

encoding_info = chardet.detect(raw_data)
detected_encoding = encoding_info["encoding"]

print(f"Detected Encoding: {detected_encoding}")

Detected Encoding: Windows-1252


In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir('my_extracted_data'):

  f = open(os.path.join('my_extracted_data', filename),"r",encoding="Windows-1252")

  corpus = f.read()
  raw_sent = sent_tokenize(corpus)

  for sent in raw_sent:
    story.append(simple_preprocess(sent))


In [ ]:
len(story)

145020

In [ ]:
story

[['clash',
  'of',
  'kings',
  'book',
  'two',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'the',
  'comet',
  'tail',
  'spread',
  'across',
  'the',
  'dawn',
  'red',
  'slash',
  'that',
  'bled',
  'above',
  'the',
  'crags',
  'of',
  'dragonstone',
  'like',
  'wound',
  'in',
  'the',
  'pink',
  'and',
  'purple',
  'sky'],
 ['the',
  'maester',
  'stood',
  'on',
  'the',
  'windswept',
  'balcony',
  'outside',
  'his',
  'chambers'],
 ['it', 'was', 'here', 'the', 'ravens', 'came', 'after', 'long', 'flight'],
 ['their',
  'droppings',
  'speckled',
  'the',
  'gargoyles',
  'that',
  'rose',
  'twelve',
  'feet',
  'tall',
  'on',
  'either',
  'side',
  'of',
  'him',
  'hellhound',
  'and',
  'wyvern',
  'two',
  'of',
  'the',
  'thousand',
  'that',
  'brooded',
  'over',
  'the',
  'walls',
  'of',
  'the',
  'ancient',
  'fortress'],
 ['when',
  'first',
  'he',
  'came',
  'to',
  'dragonstone',
  'the',
  

In [ ]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count=2,   # we will take only those sentences that have atleast two words
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story,total_examples = model.corpus_count, epochs=model.epochs)

(6569192, 8628190)

In [ ]:
model.wv.most_similar('daenerys')

[('stormborn', 0.795168399810791),
 ('targaryen', 0.7895488739013672),
 ('myrcella', 0.74002605676651),
 ('unburnt', 0.7097630500793457),
 ('princess', 0.7082334160804749),
 ('elia', 0.6966159343719482),
 ('queen', 0.6936781406402588),
 ('viserys', 0.6687658429145813),
 ('aegon', 0.6613115668296814),
 ('rhaegar', 0.641215443611145)]

In [ ]:
model.wv.doesnt_match(['jon','rikon','arya','sansa','bran'])

'jon'

In [ ]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [ ]:
model.wv['jon']

array([ 6.7684877e-01, -6.4564097e-01,  3.2577583e-01, -1.0816770e+00,
        1.5109415e+00,  4.4551364e-01, -3.2400924e-03,  2.9576311e-01,
       -1.1347919e+00,  1.4442305e-01, -1.5648643e+00, -8.3751112e-01,
       -7.5505888e-01, -4.8884481e-01,  4.2961964e-01,  6.4937145e-01,
        1.9302145e+00,  1.9416431e+00, -9.0799803e-01, -1.6618948e+00,
        2.0723920e+00, -1.6385900e+00,  8.5352701e-01,  3.4798820e+00,
       -1.0087672e+00, -7.6740032e-01,  1.8079722e+00, -4.7567123e-01,
        9.2185229e-02, -7.2563484e-02, -1.1870279e+00, -7.4445385e-01,
        7.9797673e-01, -1.4898021e+00,  1.4230448e+00,  3.8368228e-01,
        1.6758302e+00, -1.3624334e-01,  9.5156294e-01, -2.2960715e-01,
        3.1239638e-01, -1.3650672e+00,  1.1392606e+00,  1.5066987e+00,
        1.4370837e+00, -1.6556646e+00, -7.3283619e-01,  1.3361257e+00,
       -9.2109710e-01,  6.7962104e-01,  3.3402202e-01, -1.7606996e+00,
        4.7205231e-01, -8.2037330e-01, -8.8530147e-01,  1.0582462e-01,
      

In [ ]:
model.wv.similarity('arya','sansa')

0.8521433

In [ ]:
model.wv.similarity('cersei','sansa')

0.752368

In [ ]:
model.wv.similarity('tywin','sansa')

0.2359811

In [ ]:
# now we go from high dimensions to low dimensions
# for this we will be using PCA


In [ ]:
# this gives vector represntation of all the words at once
model.wv.get_normed_vectors()

array([[ 0.0038627 , -0.05085305,  0.05602812, ...,  0.00021139,
        -0.09260541,  0.11270923],
       [-0.19215982, -0.10844415, -0.03567484, ...,  0.03918358,
         0.06759756,  0.07119211],
       [ 0.11669139, -0.09953775, -0.08422518, ..., -0.03241254,
         0.04665294, -0.01641608],
       ...,
       [-0.07746138,  0.01055248,  0.00808731, ..., -0.00112936,
        -0.05135864, -0.0484291 ],
       [ 0.00264534,  0.07987279,  0.00602253, ...,  0.03736708,
         0.08076638,  0.13317879],
       [-0.09305125,  0.06751706,  0.06686883, ..., -0.08015706,
         0.0189705 ,  0.03468097]], dtype=float32)

In [ ]:
y = model.wv.index_to_key
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'tyrion',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [ ]:
model.wv.get_normed_vectors().shape
# so we are currently in 100 dimensions

(17453, 100)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=3)

In [ ]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [ ]:
X[:5]

array([[ 0.13608944,  0.5958596 , -0.04487216],
       [ 0.16235018,  0.33523637,  0.02225706],
       [-0.29293045,  0.57685995,  0.20356573],
       [ 0.01156178,  0.35014927, -0.132177  ],
       [-0.13508616,  0.5465984 ,  0.26533926]], dtype=float32)

In [ ]:
X.shape

(17453, 3)

In [ ]:
import plotly.express as px

fig = px.scatter_3d(X[:100], x=0, y=1, z=2, color=y[:100])
fig.show()

# ASSIGNMENT

In [6]:
!kaggle datasets download -d mitramir5/the-big-bang-theory-series-transcript

Dataset URL: https://www.kaggle.com/datasets/mitramir5/the-big-bang-theory-series-transcript
License(s): unknown
  0% 0.00/1.92M [00:00<?, ?B/s]
100% 1.92M/1.92M [00:00<00:00, 115MB/s]


In [7]:
!unzip -q the-big-bang-theory-series-transcript.zip -d my_extracted_data


In [8]:
df = pd.read_csv("/content/my_extracted_data/1_10_seasons_tbbt.csv")
df

episode_name  \
0                   Series 01 Episode 01 – Pilot Episode   
1                   Series 01 Episode 01 – Pilot Episode   
2                   Series 01 Episode 01 – Pilot Episode   
3                   Series 01 Episode 01 – Pilot Episode   
4                   Series 01 Episode 01 – Pilot Episode   
...                                                  ...   
54401  Series 10 Episode 24 – The Long Distance Disso...   
54402  Series 10 Episode 24 – The Long Distance Disso...   
54403  Series 10 Episode 24 – The Long Distance Disso...   
54404  Series 10 Episode 24 – The Long Distance Disso...   
54405  Series 10 Episode 24 – The Long Distance Disso...   

                                                dialogue person_scene  
0                            A corridor at a sperm bank.        Scene  
1       So if a photon is directed through a plane wi...      Sheldon  
2                             Agreed, what’s your point?      Leonard  
3       There’s no point, I just think it’s a good id...      Sheldon  
4                                             Excuse me?      Leonard  
...                                                  ...          ...  
54401   And I with you. Question, are you seeking a r...      Sheldon  
54402                                    What if I were?       Ramona  
54403   Well, that would raise a number of problems. ...      Sheldon  
54404                                        Princeton.         Scene  
54405   (Knock, knock, knock) Amy. (Knock, knock, kno...      Sheldon  

[54406 rows x 3 columns]

In [9]:
df = df['dialogue']
df

0                              A corridor at a sperm bank.
1         So if a photon is directed through a plane wi...
2                               Agreed, what’s your point?
3         There’s no point, I just think it’s a good id...
4                                               Excuse me?
                               ...                        
54401     And I with you. Question, are you seeking a r...
54402                                      What if I were?
54403     Well, that would raise a number of problems. ...
54404                                          Princeton. 
54405     (Knock, knock, knock) Amy. (Knock, knock, kno...
Name: dialogue, Length: 54406, dtype: object

In [11]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [15]:
data = df.to_string(index=False)

In [16]:
data

'                       A corridor at a sperm bank.\n So if a photon is directed through a plane wit...\n                        Agreed, what’s your point?\n There’s no point, I just think it’s a good ide...\n                                        Excuse me?\n                                         Hang on. \n One across is Aegean, eight down is Nabakov, t...\n                                   Can I help you?\n          Yes. Um, is this the High IQ sperm bank?\n  If you have to ask, maybe you shouldn’t be here.\n                        I think this is the place.\n                                   Fill these out.\n                   Thank-you. We’ll be right back.\n Oh, take your time. I’ll just finish my crossw...\n             Leonard, I don’t think I can do this.\n        What, are you kidding? You’re a semi-pro. \n No. We are committing genetic fraud. There’s n...\n Sheldon, this was your idea. A little extra mo...\n I know, and I do yearn for faster downloads, b...\n           

In [17]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
story = []
corpus = data
raw_sent = sent_tokenize(corpus)

for sent in raw_sent:
  story.append(simple_preprocess(sent))

In [19]:
story

[['corridor', 'at', 'sperm', 'bank'],
 ['so', 'if', 'photon', 'is', 'directed', 'through', 'plane', 'wit'],
 ['agreed', 'what', 'your', 'point'],
 ['there', 'no', 'point', 'just', 'think', 'it', 'good', 'ide'],
 ['excuse', 'me'],
 ['hang', 'on'],
 ['one',
  'across',
  'is',
  'aegean',
  'eight',
  'down',
  'is',
  'nabakov',
  'can',
  'help',
  'you'],
 ['yes'],
 ['um', 'is', 'this', 'the', 'high', 'iq', 'sperm', 'bank'],
 ['if', 'you', 'have', 'to', 'ask', 'maybe', 'you', 'shouldn', 'be', 'here'],
 ['think', 'this', 'is', 'the', 'place'],
 ['fill', 'these', 'out'],
 ['thank', 'you'],
 ['we', 'll', 'be', 'right', 'back'],
 ['oh', 'take', 'your', 'time'],
 ['ll',
  'just',
  'finish',
  'my',
  'crossw',
  'leonard',
  'don',
  'think',
  'can',
  'do',
  'this'],
 ['what', 'are', 'you', 'kidding'],
 ['you', 're', 'semi', 'pro'],
 ['no'],
 ['we', 'are', 'committing', 'genetic', 'fraud'],
 ['there', 'sheldon', 'this', 'was', 'your', 'idea'],
 ['little', 'extra', 'mo'],
 ['know',
  'a

In [20]:
len(story)

58092

In [21]:
model = gensim.models.Word2Vec(
    window = 16,
    min_count = 2,

)

In [22]:
model.build_vocab(story)

In [23]:
model.train(story,total_examples = model.corpus_count, epochs=model.epochs)

(1158449, 1673910)

In [24]:
model2 = Word2Vec(
    sentences=story,  # Your tokenized corpus
    vector_size=100,      # Dimensionality of word vectors
    window=10,            # Context window size
    min_count=2,          # Ignore words with frequency < 2
    workers=4,            # Use 4 CPU cores for training
)

In [25]:
model.wv.similarity("penny","leonard")

0.90665513

In [28]:
model.wv.similarity("penny","kripke")

0.6493113

In [32]:
model.wv.similarity("penny","crazy")

0.6420695

In [31]:
model.wv.similarity("sheldon","crazy")

0.8070427

In [38]:
model.wv.similarity("koothrappali","indian")

0.9647905

In [39]:
model.wv.similarity("howard","indian")

0.6338527

In [52]:
model.wv.similarity("penny","train")

0.5847596

In [49]:
model.wv.similarity("sheldon","train")

0.6902843

In [71]:
model.wv.doesnt_match(['kripke','leonard','raj','howard','sheldon'])

'kripke'

In [53]:
model.wv.get_normed_vectors()

array([[-0.16416214, -0.01148038, -0.15570016, ..., -0.17545725,
         0.04203595,  0.10818602],
       [-0.14762372,  0.09187467, -0.03243605, ..., -0.12913698,
        -0.10805699,  0.07870875],
       [-0.04702199,  0.03791442, -0.13406494, ..., -0.10618962,
         0.15015921, -0.09708497],
       ...,
       [-0.1626594 ,  0.13491541,  0.03094376, ..., -0.04071781,
         0.03527284,  0.10566923],
       [ 0.00385823,  0.02980381, -0.04060984, ..., -0.03506783,
         0.00500195, -0.12888363],
       [-0.21061572, -0.01742247, -0.095531  , ..., -0.04683691,
         0.00840374, -0.03575628]], dtype=float32)

In [55]:
y = model.wv.index_to_key
y

['you',
 'the',
 'to',
 'it',
 'that',
 'what',
 'oh',
 'we',
 'is',
 'and',
 'no',
 'of',
 're',
 'me',
 'well',
 'not',
 'don',
 'in',
 'my',
 'this',
 'know',
 'on',
 'do',
 'have',
 'just',
 'so',
 'okay',
 'are',
 'yeah',
 'can',
 'your',
 'he',
 'was',
 'sheldon',
 'for',
 'be',
 'but',
 'with',
 'if',
 'all',
 'how',
 'right',
 'like',
 'about',
 'go',
 'hey',
 'she',
 'leonard',
 'why',
 'there',
 'think',
 'get',
 'apartment',
 'did',
 'want',
 'good',
 'penny',
 'here',
 'll',
 'uh',
 'up',
 'really',
 'at',
 'going',
 'out',
 've',
 'one',
 'they',
 'yes',
 'now',
 'let',
 'got',
 'an',
 'come',
 'sorry',
 'when',
 'see',
 'would',
 'howard',
 'her',
 'look',
 'him',
 'say',
 'gonna',
 'thank',
 'didn',
 'sure',
 'who',
 'as',
 'amy',
 'were',
 'guys',
 'could',
 'great',
 'time',
 'too',
 'tell',
 'fine',
 'little',
 'been',
 'make',
 'knock',
 'had',
 'should',
 'raj',
 'need',
 'mean',
 'maybe',
 'back',
 'wait',
 'doing',
 'some',
 'take',
 'from',
 'am',
 'because',
 'w

In [56]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [57]:
X = pca.fit_transform(model.wv.get_normed_vectors())
X

array([[ 0.6104687 , -0.09226036,  0.07556619],
       [ 0.02740261, -0.24148399, -0.14274117],
       [ 0.5167194 , -0.14053321,  0.10449237],
       ...,
       [ 0.17782038,  0.01165283, -0.11270867],
       [-0.18325794, -0.01764613, -0.0816981 ],
       [ 0.20742248, -0.03353012,  0.00895905]], dtype=float32)

In [59]:
import plotly.express as px

fig = px.scatter_3d(X[:200], x=0, y=1, z=2, color=y[:200])
fig.show()