<a href="https://colab.research.google.com/github/MethEthPro/colab/blob/main/pytorch/week00/pytoch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.5.1+cu121'

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()
# this works for only one element tensor
# it will give us an integer value and not a tensor object

7

In [ ]:
# vector
vector = torch.tensor([2,4,6])
vector

tensor([2, 4, 6])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape
# The shape tells you how the elements inside them are arranged.

torch.Size([3])

In [ ]:
# Matrix
MATRIX=torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[2,4,6],[8,10,12],[14,16,18]]])
TENSOR

tensor([[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape
# as we have depth of 1 , and then a matrix of 3 x 3
# so shape becomes 1,3,3

torch.Size([1, 3, 3])

In [ ]:
TENSOR_NEW = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
TENSOR_NEW

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
# so as we can clearly see that there are 2 matrix of 3x3 , so shape will be
# 2,3,3
# you can imagine these matrixes on top of each other
TENSOR_NEW.shape

torch.Size([2, 3, 3])

In [ ]:
# creating a random tensor
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[0.3443, 0.2130, 0.5524, 0.0631],
         [0.1855, 0.8172, 0.2663, 0.9112],
         [0.4264, 0.0509, 0.2679, 0.4080]]),
 torch.float32,
 2)

In [ ]:
random_tensor_2 = torch.rand(size=(4,5,2))
print(random_tensor_2)
random_tensor_2.shape, random_tensor_2.ndim

# so we get a tensor with depth 4 , and each matrix having 5 rows and 2 columns

tensor([[[0.3704, 0.4799],
         [0.1573, 0.8113],
         [0.3635, 0.6082],
         [0.0345, 0.7388],
         [0.1743, 0.8287]],

        [[0.0090, 0.8974],
         [0.0700, 0.6782],
         [0.7646, 0.1366],
         [0.1815, 0.2176],
         [0.2225, 0.3776]],

        [[0.2983, 0.7215],
         [0.3172, 0.7929],
         [0.0964, 0.5221],
         [0.8874, 0.9991],
         [0.9390, 0.4951]],

        [[0.9739, 0.2427],
         [0.5811, 0.7157],
         [0.7816, 0.3196],
         [0.8995, 0.6431],
         [0.4500, 0.4291]]])


(torch.Size([4, 5, 2]), 3)

In [ ]:
# creating a tensor of all zeros or all ones
tens_zer = torch.zeros(size=(2,3))
tens_zer

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
tens_one = torch.ones(size=(2,2,3))
tens_one

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
# creating a range like tensor
# we can use torch.arange(start,end,step)
# where start value is included but the end value is not included
zero_to_ten = torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# if you want a tensor of the same shape as that of another tensor you can use
# zeros_like(input=tensor_name) or ones_like(input=tensoe_name)
my_zero = torch.zeros_like(input=random_tensor)
my_zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
my_ones = torch.ones_like(input=random_tensor_2)
my_ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
# default datatype for tensors is float32
my_tensor = torch.tensor([[12.0,16.0,20.0],[24.0,28.0,32.0]],
                         dtype=None,
                         device=None,
                         requires_grad=False  #if true operations performed on the tensors are recorded
                         )
print(my_tensor)
my_tensor.shape, my_tensor.dtype, my_tensor.device,my_tensor.ndim

tensor([[12., 16., 20.],
        [24., 28., 32.]])


(torch.Size([2, 3]), torch.float32, device(type='cpu'), 2)

In [ ]:
my_tensorr=torch.tensor([[1,2,3],[4,5,6]],
                        dtype=torch.float64)
my_tensorr,my_tensorr.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float64),
 torch.float64)

In [ ]:
cuda0 = torch.device('cuda:0')
my_new_tensor = torch.tensor([[12,10,8],[6,4,2]],
                             dtype=torch.float64,
                             device=cuda0,
                             requires_grad=False,
                             )
print(my_new_tensor)
my_new_tensor.shape, my_new_tensor.dtype, my_new_tensor.device

# ab nvidia ka gpu kaaha se laaauuuu

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

commonly we get 3 types of information from a tensor , these include its shape,datatype and where it is stored , the cpu or gpu

In [ ]:
# BASIC OPERATIONS
# ADDITION
# SUBTRACTION
# MULTIPLICATION(ELEMENT WISE)
# DIVISION
# MATRIX MULTIPLICATION

In [ ]:
tensor = torch.tensor([[2,4,6],[8,10,12]])
tensor

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
tensor*2

tensor([[ 4,  8, 12],
        [16, 20, 24]])

In [ ]:
tensor
# so we see that values inside tensor dont change unless it is reassigned

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
tensor = tensor * 2
tensor

tensor([[ 4,  8, 12],
        [16, 20, 24]])

In [ ]:
tensor = tensor + 2
tensor

tensor([[ 6, 10, 14],
        [18, 22, 26]])

In [ ]:
tensor = tensor -2
tensor

tensor([[ 4,  8, 12],
        [16, 20, 24]])

In [ ]:
tensor = tensor / 2
tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [ ]:
tensor_1 = torch.tensor([[1,2,3],[1,2,3]])
tensor_2 = torch.tensor([[2,2,2],[2,2,2],[2,2,2]])
tensor_1*tensor_1

tensor([[1, 4, 9],
        [1, 4, 9]])

In [ ]:
tensor_2*tensor_2

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [ ]:
tensor_1*tensor_2
# so to multiply two tensors elementwise they should be of the same order/shape

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

MATRIX MULTIPLICATION

In [ ]:
# we use @ symbol for matrix multiplication
# rememeber the condition of orders of the matrices for matrix multiplication
# to be possible, and what orders they give in return

In [ ]:
# both tensors are one dimensional , the dot product(scalar) is returned
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([2,4,6])
torch.matmul(tensor_1, tensor_2)
# we get 28 = 1*2 + 2*4 + 6*3  (dot product)

tensor(28)

In [ ]:
# we can do the same thing manually but we avoid using for loops , as they are computationally expensive

%%time
value = 0
for i in range(len(tensor_1)):
  value += tensor_1[i] * tensor_2[i]
value

CPU times: user 1.86 ms, sys: 0 ns, total: 1.86 ms
Wall time: 1.97 ms


tensor(28)

In [ ]:
%%time
torch.matmul(tensor_1, tensor_2)
# so this is much faster , and thus we avoid doing matrix multiplication by hand

CPU times: user 93 µs, sys: 8 µs, total: 101 µs
Wall time: 106 µs


tensor(28)

In [ ]:
# if we have a matrix X matrix multiplication
# i.e both the tensors have a dimension of 2 or more
tensor_3 = torch.tensor([[1,2,3],[4,5,6]])  # order is 2x3
tensor_4 = torch.tensor([[6,7,9,10],[11,12,13,14],[15,16,17,18]]) # order is 3x4
# so matrix multiplication should give us 2x4 matrix1


In [ ]:
%%time
torch.matmul(tensor_3, tensor_4)

CPU times: user 120 µs, sys: 11 µs, total: 131 µs
Wall time: 135 µs


tensor([[ 73,  79,  86,  92],
        [169, 184, 203, 218]])

In [ ]:
len(tensor_3)

2

In [ ]:
len(tensor_4[0])

4

In [ ]:
len(tensor_4)

3

In [ ]:
%%time
value = 0
rows = len(tensor_3)
columns = len(tensor_4[0])
common = len(tensor_4)  # it is either the number of columns of tensor 3 or number of rows of tensor_4
new_tensor = torch.zeros(size=(rows,columns))
for i in range(rows):
  for j in range(columns):
    for k in range(common):
      new_tensor[i][j] += tensor_3[i][k] * tensor_4[k][j]

new_tensor
# we can clearly see the time difference

CPU times: user 3.21 ms, sys: 0 ns, total: 3.21 ms
Wall time: 3.17 ms


tensor([[ 73.,  79.,  86.,  92.],
        [169., 184., 203., 218.]])

**SHAPE ERRORS**

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)
tensor_B = torch.tensor([[7,10],[8,11],[9,12]], dtype=torch.float32)

In [ ]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# now clearly as they both have order of 3x2 and 3x2 , there matrix mul is not possible
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# so we try to change the order of matrix B , we can do that by taking its transpose
# we can do that by 2 methods
# torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
# tensor.T - where tensor is the desired tensor to transpose.

In [ ]:
print(tensor_A)
print(tensor_B.T)
# now these 2 maatrices have order of 3x2 and 2x3 so mat mul is possible ,
# and will give us a resulting matrix of order 3x3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# mm can also be used instead of matmul
output = torch.mm(tensor_A,tensor_B.T)
print(output)
print(output.shape)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
torch.Size([3, 3])


In [ ]:
# torch.nn.Linear() also called as feed forward layer implements a
# matrux multiplication between an input x and a weights matrix A
# y=xA.T + b
# y is the output
# x is the input
# A is the wieghts matrix , we are taking its transpose , can be represented by  w also
# b is the bias or the offset by which we offset the the weights and input

In [ ]:
print(tensor_A)
tensor_A.shape

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


torch.Size([3, 2])

In [ ]:
# playing with linear layer  torch.nn.Linear()
torch.manual_seed(42)
# this is basically a matrix multiplication
linear = torch.nn.Linear(in_features=2,  #it matches inner dimension of input
                         out_features=6) #it describes outer value

x=tensor_A
# we saw earlier that shape of tensor _A is 3x2 and
# so we are multiplying 3x2 with 2x6,
# this will give us a 3x6 matrix
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

# in features is basically the # of columns of 1st matrix and  # of rows of 2nd matrix , basically the inner dimension of the 2 matrices
# and out features is basically the columns of the output matrix, or the columns of the 2nd input matrix

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
# playing with linear layer  torch.nn.Linear()
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3,
                         out_features=5)

x=tensor_A.T
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([2, 3])

Output:
tensor([[1.1212, 1.1785, 3.3663, 1.3527, 2.2002],
        [1.9066, 1.6988, 3.9332, 1.5390, 2.9834]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 5])


min,max,mean,sum

In [ ]:
x = torch.arange(start=10, end=100, step=10)
x

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# so there are 2 methods to get these and notice that
# for mean we need to pass the type also
print(x.min())
print(torch.min(x))
print(x.max())
print(torch.max(x))
print(x.sum())
print(torch.sum(x))
print(x.type(torch.float32).mean())
print(torch.mean(x.type(torch.float32)))


tensor(10)
tensor(10)
tensor(90)
tensor(90)
tensor(450)
tensor(450)
tensor(50.)
tensor(50.)


In [ ]:
# we can also get the index of the min and max value
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(8)


In [ ]:
# changing tensor datatypes
x.dtype

torch.int64

In [ ]:
x_32 = x.type(torch.int32)
x_16 = x.type(torch.float16)
print(x_32.dtype,x_32)
print(x_16.dtype,x_16)

torch.int32 tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int32)
torch.float16 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


In [ ]:
# 10-min-gang
x=torch.tensor([[2,3,4,5],[6,7,8,9]])
y=x.new_tensor([2,3,5])
print(y)
print(x)

tensor([2, 3, 5])
tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])


In [ ]:
y=x.new_full(size=(4,3),fill_value=12)
y

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])

In [ ]:
y=x.new_empty(size=(4,3))
y

tensor([[134145027932208, 134141256709200, 134141256709152],
        [134141254549232, 134145025425696, 134141256709728],
        [134145024409264, 134141254548976, 134145025425696],
        [134141256707184, 134144986827888, 134141251003888]])

In [ ]:
y=x.new_ones(size=(4,3))
y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
y=x.new_zeros(size=(4,3))
y

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
x.is_cuda
# Is True if the Tensor is stored on the GPU, False otherwise.

False

In [ ]:
x.is_quantized
# Quantizing a tensor refers to reducing the precision of its values to make computations more efficient, especially in contexts like deep learning on edge devices or mobile platforms.
#  It's commonly used to reduce memory usage and increase computational speed while maintaining acceptable accuracy.

False

In [ ]:
x.is_meta
# Is True if the Tensor is a meta tensor, False otherwise

False

In [ ]:
# Create a meta tensor
meta_tensor = torch.empty(3, 4, device="meta")

print(meta_tensor)  # Tensor with shape (3, 4) but no data

tensor(..., device='meta', size=(3, 4))


In [ ]:
meta_tensor.is_meta

True

In [ ]:
x.device

device(type='cpu')

In [ ]:
x.ndim

2

In [ ]:
x.real

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [ ]:
x.imag

RuntimeError: imag is not implemented for tensors with non-complex dtypes.

In [ ]:
x.dtype

torch.int64

In [ ]:
x.nbytes

64

In [ ]:
x.abs()

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [ ]:
# a little about autograd
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()   # To compute gradients, you call .backward() on a scalar tensor (usually a loss function).
# here out is of the form x^2 , so on diff wrt x we get , 2x
# so on calling x.grad we get 2x
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [ ]:
# another example

# Define a tensor with gradient tracking
x = torch.tensor(2.0, requires_grad=True)

# Perform operations (forward pass)
y = x ** 2 + 3 * x

# Compute gradients (backward pass)
y.backward()

# Gradient of y with respect to x
print(x.grad)  # dy/dx = 2*x + 3 = 2*2 + 3 = 7


tensor(7.)


reshaping,stacking,squeezing and unsqueezing

In [ ]:
x=torch.arange(1.,8.)
x, x.shape ,x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [ ]:
# reshaping
# adding a dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [ ]:
# removing a dimension
x_reshaped_2 = x_reshaped.reshape(7)
x_reshaped_2, x_reshaped_2.shape, x_reshaped_2.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [ ]:
# torch.view()
z=x.view(1,7)
z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
print(x.shape, x.ndim)

torch.Size([7]) 1


In [ ]:
x=torch.arange(1.,8.)

In [ ]:
# stacking tensors on top of each other
x_stack = torch.stack([x,x,x,x], dim = 0)

print(x_stack, x_stack.shape, x_stack.ndim)

# if we put dim = 0, it stacks the tensors horizontally

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]]) torch.Size([4, 7]) 2


In [ ]:
x_stack = torch.stack([x,x,x,x], dim = 1)

print(x_stack, x_stack.shape, x_stack.ndim)
# if we put dim = 1 , it stacks the tensors vertically

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]]) torch.Size([7, 4]) 2


In [ ]:
# squeezing and unsqeezing

# we can do squeezing to remove all 1 dimensions from a tensor

print(x_reshaped, x_reshaped.ndim, x_reshaped.shape)

tensor([[5., 2., 3., 4., 5., 6., 7.]]) 2 torch.Size([1, 7])


In [ ]:
x_squeezed = x_reshaped.squeeze()

print(x_squeezed, x_squeezed.ndim, x_squeezed.shape)

tensor([5., 2., 3., 4., 5., 6., 7.]) 1 torch.Size([7])


In [ ]:
# we can also add a dimension by using unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.ndim, x_unsqueezed.shape)

tensor([[5., 2., 3., 4., 5., 6., 7.]]) 2 torch.Size([1, 7])


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed, x_unsqueezed.ndim, x_unsqueezed.shape)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]]) 2 torch.Size([7, 1])


In [ ]:
# we can also rearrange the shape with the help of permute
x=torch.rand(size=(220,221,222))
print(x.shape)

x_permute= x.permute(1,2,0)
print(x_permute.shape)

# this just shifts axis so now , 0-->1 , 1-->2 , 2-->0
# this works just lile view , so if you make changes in x_permute
# similar changes will reflect in x

torch.Size([220, 221, 222])
torch.Size([221, 222, 220])


In [ ]:
# INDEXING
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][0]

tensor(4)

In [ ]:
x[0,:,2]  #3rd column

tensor([3, 6, 9])

In [ ]:
x[0][1] # 2nd row

tensor([4, 5, 6])

In [ ]:
import numpy as np

In [ ]:
# pytorch tensors and numpy , we can convert them form one form to another
# numpy to pytorch tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, array.dtype,tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
# from tensor to numpy
x = torch.ones(7)
my_array = x.numpy()

x,my_array


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility , we set a manual seed to limit the randomness or give it a flavor

In [ ]:
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.2045, 0.4096, 0.7911, 0.3289],
        [0.8452, 0.9631, 0.8412, 0.9319],
        [0.2626, 0.6265, 0.2968, 0.0763]])
tensor([[0.5386, 0.2221, 0.1170, 0.7985],
        [0.6773, 0.1425, 0.1513, 0.6256],
        [0.9912, 0.3122, 0.8270, 0.5236]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED=42

torch.manual_seed(seed=RANDOM_SEED)
tensor_A = torch.rand(3,4)
torch.manual_seed(seed=RANDOM_SEED)
tensor_B = torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
lspci | grep VGA

SyntaxError: invalid syntax (<ipython-input-168-0653cb4dd97f>, line 1)

In [ ]:
torch.cuda.is_avaialble()

AttributeError: module 'torch.cuda' has no attribute 'is_avaialble'

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3]) cpu


In [ ]:
# moving back to cpu
# tensor_name.cpu().any_operation
# eg  tensor_name.cpu().numpy()
# as numpy arrays dont work on gpu tensors

# **EXERCISES**

In [ ]:
# 2
my_tensor = torch.rand(size=(7,7))
my_tensor

tensor([[0.4742, 0.3583, 0.7055, 0.6613, 0.1568, 0.8996, 0.8749],
        [0.3203, 0.2300, 0.2886, 0.3450, 0.6449, 0.4961, 0.3373],
        [0.0683, 0.9873, 0.7637, 0.5431, 0.0268, 0.6475, 0.5900],
        [0.9524, 0.3917, 0.9342, 0.5656, 0.0705, 0.6009, 0.6590],
        [0.6150, 0.0784, 0.1582, 0.4858, 0.3408, 0.3651, 0.0048],
        [0.6004, 0.6545, 0.9008, 0.9215, 0.3718, 0.7380, 0.6952],
        [0.9436, 0.1409, 0.8321, 0.5733, 0.8042, 0.9258, 0.3363]])

In [ ]:
my_tensor_2 = torch.rand(size=(1,7))
# to do mat mul we have 7x7 and 1x7 , so we will have to take transpose of the second matrix
# we will get 7x7 and 7x1 , to give us a resulting matrix of order 7x1
mul = torch.matmul(my_tensor, my_tensor_2.T)
mul, mul.shape

(tensor([[1.7519],
         [1.0899],
         [1.3220],
         [1.4455],
         [0.6422],
         [1.8220],
         [1.5905]]),
 torch.Size([7, 1]))

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
my_tensor = torch.rand(size=(7,7))
torch.manual_seed(seed=RANDOM_SEED)
my_tensor_2 = torch.rand(size=(1,7))
mul = torch.matmul(my_tensor, my_tensor_2.T)
mul, mul.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [ ]:
RANDOM_SEED = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED)
my_tensor = torch.rand(size=(2,3)).to(device)
torch.cuda.manual_seed(seed=RANDOM_SEED)
my_tensor_2 = torch.rand(size=(2,3)).to(device)
mul = torch.matmul(my_tensor, my_tensor_2.T)
mul, mul.shape

(tensor([[0.8386, 0.5860],
         [1.0676, 0.5279]]),
 torch.Size([2, 2]))

In [ ]:
print(mul.min())
print(mul.max())

tensor(0.2161)
tensor(0.6287)


In [ ]:
print(mul.argmin())
print(mul.argmax())

tensor(1)
tensor(3)


In [ ]:
RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)

new_tensor = torch.rand(size=(1,1,1,10))
print(new_tensor, new_tensor.shape)

new_tensor_squeezed = new_tensor.squeeze()
print(new_tensor_squeezed,new_tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
